.read data_actor.sql
.read data_address.sql
.read data_category.sql
.read data_city.sql
.read data_country.sql
.read data_customer.sql
.read data_film.sql
.read data_film_actor.sql
.read data_film_category.sql
.read data_inventory.sql
.read data_language.sql
.read data_payment.sql
.read data_rental.sql
.read data_staff.sql
.read data_store.sql